### PR TITLE
(winnie) Fixing edefinition of struct stat

### LINKED ISSUE #2923: Issue building under mingw64 windows msys2 - all_pairs on develop
**Problem**
Can't compile, get error:

```
src/allpairs/CMakeFiles/allpairs.dir/allpairs_process.cpp.obj -MF CMakeFiles/allpairs.dir/allpairs_process.cpp.obj.d -o CMakeFiles/allpairs.dir/allpairs_process.cpp.obj -c /E/jenkins/pgrouting/branches/develop/src/allpairs/allpairs_process.cpp
In file included from E:/jenkins/postgresql/rel/pg17w64gcc81/include/server/port.h:24,
                 from E:/jenkins/postgresql/rel/pg17w64gcc81/include/server/c.h:1370,
                 from E:/jenkins/postgresql/rel/pg17w64gcc81/include/server/postgres.h:45,
                 from E:/jenkins/pgrouting/branches/develop/include/c_common/postgres_connection.h:35,
                 from E:/jenkins/pgrouting/branches/develop/src/allpairs/allpairs_process.cpp:40:
E:/jenkins/postgresql/rel/pg17w64gcc81/include/server/port/win32_port.h:262:8: error: redefinition of 'struct stat'
 struct stat      /* This should match struct __stat64 */
        ^~~~
In file included from C:/ming64gcc81/mingw64/x86_64-w64-mingw32/include/wchar.h:424,
                 from C:/ming64gcc81/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/cwchar:44,
                 from C:/ming64gcc81/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/bits/postypes.h:40,
                 from C:/ming64gcc81/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/bits/char_traits.h:40,
                 from C:/ming64gcc81/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/string:40,
                 from E:/jenkins/pgrouting/branches/develop/src/allpairs/allpairs_process.cpp:37:
C:/ming64gcc81/mingw64/x86_64-w64-mingw32/include/_mingw_stat64.h:43:10: note: previous definition of 'struct stat'
   struct stat {
          ^~~~
make[2]: *** [src/allpairs/CMakeFiles/allpairs.dir/build.make:110: src/allpairs/CMakeFiles/allpairs.dir/allpairs_process.cpp.obj] Error 1
make[2]: Leaving directory '/projects/pgrouting/builddevelopw64gcc81'
make[1]: *** [CMakeFiles/Makefile2:1537: src/allpairs/CMakeFiles/allpairs.dir/all] Error 2
make[1]: Leaving directory '/projects/pgrouting/builddevelopw64gcc81'
make: *** [Makefile:139: all] Error 2
```
I recall we had this issue before  maybe in 3.8 which compiles fine

### PR DESCRIPTION
**Pull request by cvvergara**
Fixes #2923 

Changes proposed in this pull request:
- Reordering of include files

@pgRouting/admins

### CODE REVIEW

File: src/metrics/metrics_driver.cpp [hunk 1]
```diff
@@ -1,11 +1,11 @@
 /*PGR-GNU*****************************************************************
-File: allpairs_driver.cpp
+File: metrics_driver.cpp
```
Comment (cvvergara) [inline src/metrics/metrics_driver.cpp:2]: @Saloni-2005 
When copy/pasting make sure your adjustments are perfect

File: src/metrics/metrics_process.cpp [hunk 2]
```diff
@@ -32,23 +32,23 @@ Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
...
 
-#include <string>
-
 extern "C" {
 #include "c_common/postgres_connection.h"
 #include "c_common/e_report.h"
 #include "c_common/time_msg.h"
 }
 
+#include <string>
```
Comment (cvvergara) [inline src/metrics/metrics_process.cpp:41]: @Saloni-2005 
Probably you missed:
https://github.com/pgRouting/pgrouting/pull/2936

When you are working in a project you have to always see what is happening, in that PR the file you base your code on was modified and you didn't notice to see how or why.

File: src/ordering/ordering_process.cpp [hunk 3]
```diff
@@ -29,14 +29,14 @@ Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
...
 
-#include <string>
-
 extern "C" {
 #include "c_common/postgres_connection.h"
 #include "c_common/e_report.h"
 #include "c_common/time_msg.h"
 }
 
+#include <string>
```
Comment (cvvergara) [inline src/ordering/ordering_process.cpp:38]: @bipashabg @wifiBlack 
Probably you missed:
#2936

When you are working in a project you have to always see what is happening, in that PR the file you base your code on was modified and you didn't notice to see how or why.

File: tools/scripts/code_checker.sh [hunk 4]
```diff
@@ -47,6 +47,8 @@ INCLUDE_ORDER="
 -build/include_order:src/cpp_common/pgdata_getters.cpp,
 -build/include_order:include/cpp_common/get_data.hpp,
 -build/include_order:src/dijkstra/shortestPath_process.cpp,
+-build/include_order:src/metrics/metrics_process.cpp,
```
Comment (cvvergara) [inline tools/scripts/code_checker.sh:50]: @Saloni-2005 @bipashabg @wifiBlack 
part of the fix on the PR mentioned above

**Review by Saloni-2005 — APPROVED** [review]

**Review by wifiBlack — APPROVED** [review]
